global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'auth_service'
    static_configs:
      - targets: ['auth:3001']

  - job_name: 'user_service'
    static_configs:
      - targets: ['user:3002']

  - job_name: 'gateway_service'
    static_configs:
      - targets: ['gateway:3000']
