global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - 'alerts.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']

  - job_name: 'auth_service'
    static_configs:
      - targets: ['auth:3001']
    metrics_path: '/metrics'

  - job_name: 'user_service'
    static_configs:
      - targets: ['user:3002']
    metrics_path: '/metrics'

  - job_name: 'game_engine'
    static_configs:
      - targets: ['game:3003']
    metrics_path: '/metrics'

  - job_name: 'match_service'
    static_configs:
      - targets: ['match:3004']
    metrics_path: '/metrics'

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:3000']
    metrics_path: '/metrics'
