services:
  # redis:
  #   image: redis:7
  #   ports:
  #     - "6379:6379"


  auth:
    build:
      context: ../back/auth-service
      dockerfile: Dockerfile
      target: prod
    container_name: auth
    ports:
      - "3001:3001"
    volumes:
      - ../back/auth-service/data/:/app/data
    env_file:
    - ../back/auth-service/.env

  user:
    build:
      context: ../back/user-service
      dockerfile: Dockerfile
      target: prod
    container_name: user
    ports:
      - "3002:3002"
    volumes:
      - ../back/user-service/data/:/app/data
    env_file:
    - ../back/user-service/.env


  game:
    build:
      context: ../back/game-engine
      dockerfile: Dockerfile
      target: prod
    container_name: game
    ports:
      - "3003:3003"

  match:
    build:
      context: ../back/match-service
      dockerfile: Dockerfile
      target: prod
    container_name: match
    ports:
      - "3004:3004"

  chat:
    build:
      context: ../back/chat-service
      dockerfile: Dockerfile
    container_name: chat
    ports:
      - "3005:3005"
    volumes:
      - ../back/chat-service/data/:/app/data
    env_file:
      - ../back/chat-service/.env

  gateway:
    build:
      context: ../back/gateway
      dockerfile: Dockerfile
      target: prod
    container_name: gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - user
      - chat
    env_file:
    - ../back/gateway/.env
