services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  
  auth:
    build: ../back/auth-service
    container_name: auth
    ports:
      - "3001:3001"

  user:
    build: ../back/user-service
    container_name: user
    ports:
      - "3002:3002"
  
  game-engine:
    build: ../back/game-engine
    container_name: game-engine
    ports:
      - "3003:3003"

  match-service:
    build: ../back/match-service
    container_name: match-service
    ports:
      - "3004:3004"

  gateway:
    build: ../back/gateway
    container_name: gateway
    environment:
      JWT_SECRET: supersecret_jwt_key
      GATEWAY_SECRET: gateway_internal_secret
      AUTH_URL: http://auth:3001
      USER_URL: http://user:3002
      MATCH_SERVICE_URL: http://match-service:3004
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - user
      - match-service
