services:
  # redis:
  #   image: redis:7
  #   ports:
  #     - "6379:6379"


  auth:
    build:
      context: ../back/auth-service
      dockerfile: Dockerfile
      target: prod
    container_name: auth
    expose:
      - 3001
    volumes:
      - ../back/auth-service/data/:/app/data
    env_file:
    - ../back/auth-service/.env
    networks:
      - internal

  user:
    build:
      context: ../back/user-service
      dockerfile: Dockerfile
      target: prod
    container_name: user
    expose:
        - 3002
    volumes:
      - ../back/user-service/data/:/app/data
    env_file:
    - ../back/user-service/.env
    networks:
      - internal


  game:
    build:
      context: ../back/game-engine
      dockerfile: Dockerfile
      target: prod
    container_name: game-engine
    ports:
      - "3003:3003"
    networks:
      - internal


  match:
    build:
      context: ../back/match-service
      dockerfile: Dockerfile
      target: prod
    container_name: match
    expose:
      - 3004
    networks:
      - internal


  gateway:
    build:
      context: ../back/gateway
      dockerfile: Dockerfile
      target: prod
    container_name: gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - user
    env_file:
    - ../back/gateway/.env
    networks:
      - internal

networks:
  internal:
    driver: bridge
    internal: false