services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  
  auth:
    build: ../back/auth-service
    container_name: auth
    ports:
      - "3001:3001"
    volumes:
      - ../back/auth-service/data/:/app/data
    env_file:
    - ../back/auth-service/.env

  user:
    build: ../back/user-service
    container_name: user
    ports:
      - "3002:3002"
    volumes:
      - ../back/user-service/data/:/app/data
    env_file:
    - ../back/user-service/.env

  gateway:
    build: ../back/gateway
    container_name: gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - user
    env_file:
    - ../back/gateway/.env
