services:
  # redis:
  #   image: redis:7
  #   ports:
  #     - "6379:6379"


  auth:
    build:
      context: ../back/auth-service
      dockerfile: Dockerfile
      target: prod
    container_name: auth
    expose:
      - ${AUTH_PORT}
    volumes:
      - ../back/auth-service/data/:/app/data
    env_file:
      - .env
    networks:
      - internal

  user:
    build:
      context: ../back/user-service
      dockerfile: Dockerfile
      target: prod
    container_name: user
    expose:
        - ${USER_PORT}
    volumes:
      - ../back/user-service/data/:/app/data
    env_file:
      - .env
    networks:
      - internal


  game:
    build:
      context: ../back/game-engine
      dockerfile: Dockerfile
      target: prod
    container_name: game-engine
    ports:
      - "${GAME_PORT}:${GAME_PORT}"
    env_file:
      - .env
    networks:
      - internal


  match:
    build:
      context: ../back/match-service
      dockerfile: Dockerfile
      target: prod
    container_name: match
    expose:
      - ${MATCH_PORT}
    env_file:
      - .env
    networks:
      - internal

  chat:
    build:
      context: ../back/chat-service
      dockerfile: Dockerfile
    container_name: chat
    expose:
      - ${CHAT_PORT}
    volumes:
      - ../back/chat-service/data/:/app/data
    env_file:
      - .env
    networks:
      - internal

  interact:
    build:
      context: ../back/interact-service
      dockerfile: Dockerfile
    container_name: interact
    expose:
      - ${INTERACT_PORT}
    volumes:
      - ../back/interact-service/data/:/app/data
    env_file:
      - .env
    networks:
      - internal

  gateway:
    build:
      context: ../back/gateway
      dockerfile: Dockerfile
      target: prod
    container_name: gateway
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    depends_on:
      - auth
      - user
      - chat
      - interact
    env_file:
      - .env
    networks:
      - internal

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ../observability/monitoring/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    environment:
      - AUTH_PORT=${AUTH_PORT}
      - USER_PORT=${USER_PORT}
      - GAME_PORT=${GAME_PORT}
      - MATCH_PORT=${MATCH_PORT}
      - GATEWAY_PORT=${GATEWAY_PORT}
      - CHAT_PORT=${CHAT_PORT}
      - INTERACT_PORT=${INTERACT_PORT}
    entrypoint:
      - /bin/sh
      - -c
      - |
        sed -e 's/\$${AUTH_PORT}/'"$$AUTH_PORT"'/g' \
            -e 's/\$${USER_PORT}/'"$$USER_PORT"'/g' \
            -e 's/\$${GAME_PORT}/'"$$GAME_PORT"'/g' \
            -e 's/\$${MATCH_PORT}/'"$$MATCH_PORT"'/g' \
            -e 's/\$${GATEWAY_PORT}/'"$$GATEWAY_PORT"'/g' \
            -e 's/\$${CHAT_PORT}/'"$$CHAT_PORT"'/g' \
            -e 's/\$${INTERACT_PORT}/'"$$INTERACT_PORT"'/g' \
            /etc/prometheus/prometheus.yml > /tmp/prometheus.yml && \
        exec /bin/prometheus --config.file=/tmp/prometheus.yml \
            --storage.tsdb.path=/prometheus \
            --storage.tsdb.retention.time=15d
    ports:
      - "9090:9090"
    networks:
      - internal

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3100:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ../observability/monitoring/grafana/provisioning/:/etc/grafana/provisioning/
      - ../observability/monitoring/grafana/dashboards/:/etc/grafana/dashboards/
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    env_file:
      - .env
    networks:
      - internal

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - internal

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.22
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - internal

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.22
    container_name: logstash
    volumes:
      - ../observability/logging/logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      - ELASTIC_USER=${ELASTIC_USER:-elastic}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - XPACK_MONITORING_ELASTICSEARCH_USERNAME=${ELASTIC_USER:-elastic}
      - XPACK_MONITORING_ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - HTTP_HOST=0.0.0.0
    ports:
      - "5001:5000"
      - "9600:9600"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9600"]
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      - elasticsearch
    env_file:
      - .env
    networks:
      - internal

  elasticsearch-exporter:
    image: quay.io/prometheuscommunity/elasticsearch-exporter:latest
    container_name: elasticsearch-exporter
    command:
      - '--es.uri=http://elasticsearch:9200'
      - '--es.all'
      - '--es.indices'
    environment:
      - ES_USERNAME=${ELASTIC_USER:-elastic}
      - ES_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "9114:9114"
    depends_on:
      - elasticsearch
    env_file:
      - .env
    networks:
      - internal

  logstash-exporter:
    image: kuskoman/logstash-exporter:v1.1.0
    container_name: logstash-exporter
    environment:
      - LOGSTASH_URL=http://logstash:9600
    ports:
      - "9198:9198"
    platform: linux/amd64
    depends_on:
      logstash:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - internal

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.22
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_USERNAME=${ELASTIC_USER:-elastic}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    depends_on:
      - elasticsearch
    env_file:
      - .env
    networks:
      - internal

  frontend:
    build:
      context: ../front
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - gateway
    ports:
      - "8443:8443"
      - "8080:8080"
    volumes:
      - ./ssl:/etc/nginx/ssl
    env_file:
      - .env
    networks:
      - internal

networks:
  internal:
    driver: bridge
    internal: false

volumes:
  prometheus_data:
  grafana_data:
  elasticsearch_data:
