global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch-exporter:9114']

  - job_name: 'logstash'
    static_configs:
      - targets: ['logstash-exporter:9198']

  - job_name: 'ft_transcendence_services'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets:
        - 'auth:${AUTH_PORT}'
        - 'user:${USER_PORT}'
        - 'game-engine:${GAME_PORT}'
        - 'match:${MATCH_PORT}'
        - 'gateway:${GATEWAY_PORT}'
        - 'chat:${CHAT_PORT}'
        - 'interact:${INTERACT_PORT}'
